name: notala_apps
description: A new Flutter project.

version: 2.0.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Base
  cupertino_icons: ^1.0.5
  nb_utils: ^6.0.4
  intl: ^0.18.1
  flutter_vector_icons: ^2.0.0
  google_fonts: ^5.0.0

  #State Management Technique
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5

  # OraPay
  google_maps_flutter: ^2.3.1
  fl_chart: ^0.65.0

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.3.0
  build_runner: ^2.4.5

  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "images/orapay/oplogo.png"

flutter:

  uses-material-design: true

  assets:
   - images/orapay/
   - images/notala/
   - images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
