name: notala_apps
description: KKN NR 6 SUB KEL 3.

version: 2.0.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Base
  cupertino_icons: ^1.0.5
  nb_utils: ^6.0.4
  intl: ^0.18.1
  flutter_vector_icons: ^2.0.0
  google_fonts: ^5.0.0

  #State Management Technique
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5

  # OraPay
  google_maps_flutter: ^2.3.1
  fl_chart: ^0.64.0

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.3.0
  build_runner: ^2.4.5

  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "images/orapay/oplogo.png"

flutter:

  uses-material-design: true

  assets:
   - images/orapay/
   - images/notala/
   - images/
